version: '3'
services:
  contest:
    restart: always
    build: ContestServer
    depends_on:
      - mongo
    ports:
      - "0.0.0.0:57888:8000"
    volumes:
      - ./logs:/app/logs
      - ./contest_server.json:/app/config.json
  mongo:
    restart: always
    image: mongo:4.4.6
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
        - ./dockerdata/db:/data/db
    command: mongod
  django-client:
    restart: always
    build: DjangoContestClient
    depends_on:
      - contest
      - mongo
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./DjangoContestClient:/app
    environment:
      - CONTEST_SERVER_URL=http://contest:8000
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
