version: '3'
services:
  contest:
    restart: always
    build: ContestServer
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./contest_server.json:/app/config.json
  mongo:
    restart: always
    image: mongo
    ports:
      - "27017:27017"