version: '3'
services:
  contest:
    restart: always
    build: ContestServer
    ports:
      - "0.0.0.0:57888:8000"
    volumes:
      - ./logs:/app/logs
      - ./contest_server.json:/app/config.json
  mongo:
    restart: always
    image: mongo:4.4.6
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
        - ./dockerdata/db:/data/db
    command: mongod